"""create role

Revision ID: a8e76bfed05e
Revises:
Create Date: 2025-08-21 00:07:28.864303

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a8e76bfed05e"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    roles_table = op.create_table(
        "roles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_roles")),
    )
    op.bulk_insert(roles_table, [
        {"name": "admin"},
        {"name": "supplier"},
        {"name": "customer"},
    ])


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_table("roles")
